apiVersion: v1
kind: Secret
metadata:
  name: gitea-db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | b64enc }}
  MYSQL_USER: {{ .Values.mysql.user | b64enc }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc }}
  MYSQL_DATABASE: {{ .Values.mysql.database | b64enc }}
  GITEA_DB_PASSWD: {{ .Values.gitea.dbPassword | b64enc }}

