apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: gitea
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
  type: LoadBalancer

